### ISSUE TITLE
Printing can't handle unicode filenames

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/ion#427]
A unicode filename results in the below:
Internal Server Error: /printing
Traceback (most recent call last):
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/www/intranet3/intranet/apps/printing/views.py", line 165, in print_view
    obj = form.save(commit=True)
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/forms/models.py", line 451, in save
    self.instance.save()
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/db/models/base.py", line 728, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/db/models/base.py", line 812, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/db/models/base.py", line 851, in _do_insert
    using=using, raw=raw)
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1059, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1019, in as_sql
    for obj in self.query.objs
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1019, in <listcomp>
    for obj in self.query.objs
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1018, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 968, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/db/models/fields/files.py", line 311, in pre_save
    file.save(file.name, file, save=False)
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/db/models/fields/files.py", line 93, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/core/files/storage.py", line 53, in save
    name = self.get_available_name(name, max_length=max_length)
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/core/files/storage.py", line 89, in get_available_name
    while self.exists(name) or (max_length and len(name) > max_length):
  File "/usr/local/virtualenvs/ion/lib/python3.4/site-packages/django/core/files/storage.py", line 294, in exists
    return os.path.exists(self.path(name))
  File "/usr/local/virtualenvs/ion/lib64/python3.4/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf1' in position 46: ordinal not in range(128)

**Comment by pefoley2** [comment]
Figured it out, LANG=en_US.UTF-8 needed to be set in the supervisorctl config.
