### ISSUE TITLE
OAuth Applications can't access /api/blocks/<pk>

### ISSUE THREAD

**Issue by jediguy13** [tjcsl/ion#524]
Just like the title says. Oddly enough, `/api/blocks`, `/api/schedule`, and `/api/announcements` still work.
Check out signage2, touch-map branch to see the full code, or try this:
```python
from oauthlib.oauth2 import BackendApplicationClient
from requests_oauthlib import OAuth2Session

class Requester:
    def __init__(self, o_id, o_secret):
        self.id = o_id
        self.secret = o_secret
        self.session = None

    def refresh_session(self):
        client = BackendApplicationClient(client_id = self.id)
        self.session = OAuth2Session(client = client)
        token = self.session.fetch_token(token_url = 'https://ion.tjhsst.edu/oauth/token', 
                                       client_id = self.id,
                                       client_secret = self.secret)
        print(token)
        
    def get(self, url):
        if self.session is None:
            self.refresh_session()
        
        return self.session.get(url).json()

req = Requester(OAUTH_ID, OAUTH_SECRET) # generate those using https://ion.tjhsst.edu/oauth
print(req.get("https://ion.tjhsst.edu/api/blocks/3311"))
```

What could be causing this issue? The web api works fine for this.

**Comment by naitian** [comment]
What error do you get when making a request to that endpoint?

**Comment by jediguy13** [comment]
A JSON only containing `{'details':['An unknown error occurred.']}`

**Comment by jediguy13** [comment]
The file [/apps/api/utils.py](https://github.com/tjcsl/ion/blob/master/intranet/apps/api/utils.py) says the error should be logged when that response is returned.

**Comment by ezwang** [comment]
```
Traceback (most recent call last):
  File "/usr/local/virtualenvs/ion/lib/python3.5/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/www/intranet3/intranet/apps/eighth/views/api.py", line 76, in get
    return Response(serializer.data)
  File "/usr/local/virtualenvs/ion/lib/python3.5/site-packages/rest_framework/serializers.py", line 534, in data
    ret = super(Serializer, self).data
  File "/usr/local/virtualenvs/ion/lib/python3.5/site-packages/rest_framework/serializers.py", line 263, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/virtualenvs/ion/lib/python3.5/site-packages/rest_framework/serializers.py", line 501, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/virtualenvs/ion/lib/python3.5/site-packages/rest_framework/fields.py", line 1754, in to_representation
    return method(value)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/usr/local/www/intranet3/intranet/apps/eighth/serializers.py", line 155, in fetch_activity_list_with_metadata
    favorited_activities = set(user.favorited_activity_set.values_list("id", flat=True))
AttributeError: 'NoneType' object has no attribute 'favorited_activity_set'
```
The problem looks like it tries to access the current user object, which is not available if you use client credentials.
