### ISSUE TITLE
Diagnose intermittent connection failures to FCPS emergency page

### ISSUE THREAD

**Issue by theo-o** [tjcsl/ion#762]
From https://travis-ci.org/tjcsl/ion/jobs/569530560
It appears that the Travis workers intermittently cannot connect to the FCPS emergency page.  We should diagnose this issue.
```
HTTPSConnectionPool(host='www.fcps.edu', port=443): Max retries exceeded with url: /alert_msg_feed?26088265 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f91aaec50>, 'Connection to www.fcps.edu timed out. (connect timeout=5)'))

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn

    (self._dns_host, self.port), self.timeout, **extra_kw)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection

    raise err

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection

    sock.connect(sa)

socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen

    chunked=chunked)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/urllib3/connectionpool.py", line 344, in _make_request

    self._validate_conn(conn)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn

    conn.connect()

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/urllib3/connection.py", line 316, in connect

    conn = self._new_conn()

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/urllib3/connection.py", line 165, in _new_conn

    (self.host, self.timeout))

urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f91aaec50>, 'Connection to www.fcps.edu timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/requests/adapters.py", line 449, in send

    timeout=timeout

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen

    _stacktrace=sys.exc_info()[2])

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment

    raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.fcps.edu', port=443): Max retries exceeded with url: /alert_msg_feed?26088265 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f91aaec50>, 'Connection to www.fcps.edu timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch

    response = handler(request, *args, **kwargs)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/rest_framework/decorators.py", line 55, in handler

    return func(*args, **kwargs)

  File "/home/travis/build/tjcsl/ion/intranet/apps/emerg/api.py", line 16, in emerg_status

    return Response(get_emerg())

  File "/home/travis/build/tjcsl/ion/intranet/apps/emerg/views.py", line 83, in get_emerg

    result = get_emerg_result()

  File "/home/travis/build/tjcsl/ion/intranet/apps/emerg/views.py", line 67, in get_emerg_result

    status, message = check_emerg()

  File "/home/travis/build/tjcsl/ion/intranet/apps/emerg/views.py", line 31, in check_emerg

    r = requests.get("{}?{}".format(settings.FCPS_EMERGENCY_PAGE, int(time.time() // 60)), timeout=timeout)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/requests/api.py", line 75, in get

    return request('get', url, params=params, **kwargs)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/requests/api.py", line 60, in request

    return session.request(method=method, url=url, **kwargs)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/requests/sessions.py", line 533, in request

    resp = self.send(prep, **send_kwargs)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/requests/sessions.py", line 646, in send

    r = adapter.send(request, **kwargs)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/requests/adapters.py", line 504, in send

    raise ConnectTimeout(e, request=request)

requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.fcps.edu', port=443): Max retries exceeded with url: /alert_msg_feed?26088265 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f91aaec50>, 'Connection to www.fcps.edu timed out. (connect timeout=5)'))````

**Comment by TigerCodeHub** [comment]
Travis retired, and the check emergency function now handles timeouts - issue should be closed.
